name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: yarn install
        run: |
          yarn install
      - name: yarn build
        run: |
          yarn build
        env:
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          API_LANG: ${{ secrets.API_LANG }}
          API_COUNTRY: ${{ secrets.API_COUNTRY }}
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}