name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: yarn install
        run: |
          yarn install
      - name: yarn build
        run: |
          yarn build
        env:
          FRONTEND_URL: http://localhost:3000
          API_KEY: 9a31326bc179b029cd4513c489628e79
          API_LANG: en-US
          API_COUNTRY: GB
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"